name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        SQLITE_DB: test.db
      run: |
        pytest --cov=app tests/
        
    - name: Lint code
      run: |
        flake8 app tests
        black --check app tests
        isort --check-only app tests
        mypy app

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: v2v-email-server:test
        
    - name: Test Docker image
      run: |
        docker run --rm v2v-email-server:test python -c "import fastapi; print('FastAPI installation successful')"
        docker run --rm v2v-email-server:test python -c "import aiosqlite; print('SQLite installation successful')" 